import "@/app/globals.css";

import { NavBar } from "@/app/_component/nav-bar";
import { Provider } from "@/app/_component/provider";

import type { Metadata } from "next";

import { Noto_Sans_JP } from "next/font/google";
import type { ReactNode } from "react";

const noteSansJp = Noto_Sans_JP({
	subsets: ["latin"],
	weight: "400",
});

export const metadata: Metadata = {
	title: "e2e lesson",
	description: "Generated by create next app",
};

// export const viewport: Viewport = {
// 	width: "device-width",
// 	initialScale: 1,
// };

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html className={noteSansJp.className} lang="ja">
			<body>
				<Provider>
					{/* <MonitorSession /> */}
					<NavBar />
					{children}
				</Provider>
			</body>

			{/*
      TODO: GTMの設定をする
      https://zenn.dev/chot/articles/introduction-of-next-third-parties
      */}
			{/* <GoogleTagManager gtmId="GTM-XYZ" /> */}
		</html>
	);
}
